baseURL = 'https://geeneglungo.pages.dev/'
languageCode = 'en-us'
title = "Geene Glungo"
theme = "smol"

enableRobotsTXT = true

rssLimit = 100

# Parameters
[params]
    subtitle = ""
    dateFmt = "02.01.2006 15:04"
  [params.hugomods]
    [params.hugomods.images]
      modern_format = 'webp'

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 4

# Footer

    [[menu.footer]]
        name = "Mastodon"
        url = "https://mastodon.social/@geeneglungo"
        weight = 1

    [[menu.footer]]
        name = "YouTube"
        url = "https://youtube.com/@geeneglungo"
        weight = 2

    [[menu.footer]]
        name = "RSS"
        url = "/index.xml"
        weight = 3

[outputs]
  home = ["HTML", "RSS"]

[Author]
    name = "Geene Glungo"
    email = "geeneglungo@proton.me"

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'